# Generated by Django 5.0.7 on 2024-08-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_ingrediente_remove_receita_ingredientes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Categorias',
        ),
    ]
