# Generated by Django 5.0.7 on 2024-08-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_rename_receita_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='imagem',
            field=models.ImageField(upload_to='Categorias/'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='ingredientes',
            field=models.ManyToManyField(related_name='Categorias', to='receitas.ingrediente'),
        ),
    ]
