# Generated by Django 5.0.7 on 2024-08-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_categorias_imagem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
