# Generated by Django 5.0.7 on 2024-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_rename_categorias_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='ingredientes',
            field=models.ManyToManyField(related_name='Categoria', to='receitas.ingrediente'),
        ),
    ]
