# Generated by Django 5.0.7 on 2024-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
