# Generated by Django 5.0.7 on 2024-08-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
