# Generated by Django 5.0.7 on 2024-08-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('GALAXIA', 'galaxia'), ('PLANETA', 'planeta')], default='', max_length=100),
        ),
    ]
