# Generated by Django 5.0.7 on 2024-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('GALAXIA', 'galaxia'), ('PLANETA', 'planeta')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
