# Generated by Django 5.1.2 on 2024-10-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_author_receita_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='author',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
