# Generated by Django 5.1.5 on 2025-01-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
